---
title: Diffusion equations
jupyter: python3
---



```{python}
import numpy as np

from scipy.integrate import solve_ivp
from scipy.interpolate import interp1d

import matplotlib.pyplot as plt
import matplotlib.cm as cm

from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets

from differentials import *
```

## Linear diffusion equation (heat equation, Dynamics and Relativity Sheet 1 Question 8)

The diffusion equation $$ y_t = D y_{xx} $$ on the infinite domain
$x \in \mathbb{R}$, with $y \rightarrow 0$ as $x \rightarrow \pm\infty$,
has the similarity solution $$
y_s(x, t) = \frac{Q}{\sqrt{4\pi D t}} \exp\left(\frac{-x^2}{4Dt}\right), \qquad
Q = \int_{-\infty}^{\infty} y(x, 0) \, \mathrm{d}t
$$ Given any initial condition $y(x, 0)$ that is localised, it can be
shown that, for $t\gg1$, the solution $y(x,t)$ approaches the similarity
solution.

(The precise definition of this is subtle, and the result can be derived
using Fourier transforms and Laplace’s method for estimating large
integrals. It is related to the central limit theorem in probability
theory, and proved using similar techniques. See the *Methods* and
*Asymptotic Methods* courses.)

The similarity solution can be derived using dimensional analysis. For
$t\gg1$ it is assumed that all the details about the initial conditions
are ‘forgotten’ due to the smoothing nature of diffusion. Therefore, the
resulting solution at a point $x$ may depend only on $x$, $t$, $D$, and
the total quantity $Q = \int_{-\infty}^\infty y \,\mathrm{d}t$, which is
conserved.

The only way in which $x$, $t$ and $D$ may be combined into a
dimensionless quantity is through $s = x/\sqrt{Dt}$. Thus, whatever the
similarity solution $y_s(x, t)$ may be, it may depend on $x$ only
through the nondimensional group $s = x/\sqrt{Dt}$.

In this demo, we have chosen units in which $D = 1$. We let the initial
condition $y(x, 0)$ be some arbitrary wiggly function, concentrated
around $x=0$. It shall be seen that, whatever the shape the ic may take,
the function quickly loses that detail and approaches the shape of the
similarity solution.

```{python}
dx = 0.1
xs = np.arange(-10, 10, dx)


def y0(x):
    return np.where(abs(x) < 1, 1 + 0.3*x + 0.2 * np.sin(6*x), 0)

y0s = y0(xs)

def dydt(t, ys):
    d2ydx2 = (np.roll(ys, -1) - 2*ys + np.roll(ys, 1)) / dx**2
    return d2ydx2


sol = solve_ivp(dydt, (0, 1), y0s)
assert sol.success, sol.status

ysol = interp1d(sol.t, sol.y)
```

```{python}
@interact(t=widgets.FloatSlider(min=sol.t[0], max=sol.t[-1], step=0.01, continuous_update=False))
def diffusion_spread(t):
    q = np.sum(y0s) * dx
    if t > 0:
        y_sim = q * (4 * np.pi * t)**(-0.5) * np.exp(-xs**2 / (4*t))
    else:
        y_sim = np.where(np.abs(xs) < dx, q / dx, 0)

    fig, axs = plt.subplots()

    plt.plot(xs, ysol(t), 'k-')
    plt.plot(xs, y_sim, 'r--')
    axs.set_ylim([0, np.max(sol.y) + 0.1])
    axs.legend(('Actual solution', 'Similarity solution'))
    plt.show()
```

## Nonlinear diffusion (Mathematical Biology Sheet 3 Question 6)

One problem with the linear diffusion equation as a model is that
‘information travels infinitely fast’ - that is, we can have $y(x, t)
\neq 0$ for arbitrarily large $x$ and arbitrary small $t$ despite $y(x,
0)$ being localised.

This behaviour is not exhibited by some nonlinear diffusion equations.

$$ C_t = k (C^p C_x)_x $$

We see that when the diffusion coefficient is not constant but depends
on $C$ then ‘information does not travel infinitely fast’. Instead, a
front forms.

```{python}
dx = 0.05
xs = np.arange(-10, 10, dx)

y0s = np.where(abs(xs) < 1, 1 + np.sin(xs), 0)

def dydt(t, ys):
    yx = np.concatenate([[0], (ys[2:] - ys[:-2])/(2*dx), [0]])
    yxx = np.concatenate([[0], (ys[2:] - 2*ys[1:-1] + ys[:-2])/dx**2, [0]])
    return yx**2 + ys * yxx

sol = solve_ivp(dydt, (0, 10), y0s, method='Radau')
assert sol.success, sol.message

ysol = interp1d(sol.t, sol.y)
```

```{python}
@interact(t=widgets.FloatSlider(min=sol.t[0], max=sol.t[-1], continuous_update=False))
def diffusion_spread(t):
    fig, axs = plt.subplots()

    plt.plot(xs, ysol(t))
    axs.set_ylim([0, np.max(sol.y) + 0.1])
    plt.show()
```

## Bistable system

The equation
$$
y_t = y_{xx} - y(y-r)(y-1)
$$
with a parameter $0 < r < 1$ is an example of a bistable system. In the
absence of the diffusion term $y_{xx}$, the states $y=0$ and $y=1$ are
stable and the intermediate state $y=r$ is an unstable equilibrium.

When spatial variation and diffusion are turned back on, the "frontiers"
between regions of $y=0$ and regions of $y=1$ smooths out and moves,
eventually forming self-similar travelling waves.

In the following demo, we start with an approximately rectangular
profile, with $y = h_0$ in a region of width $w_0$ and $y = 0$ outside.
This models a "colony-forming" behaviour, where a population is
introduced to a localised region. Depending on the relative sizes of
$h_0$, $w_0$ and $r$, the colony either survives and spreads, or dies
out.


```{python}
r = 0.25
h0 = 0.2
w0 = 2
tmax = 20

xs, dx, eye, ddx, d2dx2 = discretise(-50, 50, nx=201, periodic=False)

y0s = 0.5 * h0 * (np.tanh((xs+w0/2)/0.2) - np.tanh((xs-w0/2)/0.2))

def dydt(t, ys):
    yxx = d2dx2 @ ys
    yt = yxx  - ys * (ys - r) * (ys - 1)
    yt[0] = 0
    yt[-1] = 0
    return yt

sol = solve_ivp(dydt, (0, tmax), y0s, method='RK45')
assert sol.success, sol.message
```

```{python}
ysol = interp1d(sol.t, sol.y)
```

```{python}
fig, ax = plt.subplots()
for t in np.linspace(0, tmax, 10):
    ax.plot(xs, ysol(t), c = cm.viridis(t/tmax))
ax.hlines([0, r, 1], xs[0], xs[-1], color='k', ls='--')
ax.set_ylim([-0.2, 1.2])
plt.show()
```

```{python}
@interact(t=widgets.FloatSlider(min=sol.t[0], max=sol.t[-1], continuous_update=False))
def diffusion_spread(t):
    fig, ax = plt.subplots()

    ax.plot(xs, ysol(t), 'r-')
    # ax.set_ylim([0, np.max(sol.y) + 0.1])
    ax.hlines([0, r, 1], xs[0], xs[-1], color='k', ls='--')
    ax.set_ylim([-0.2, 1.2])
    plt.show()
```




