---
title: Distributions and delta functions
jupyter: python3
---


The concept of a **distribution** comes up in probability theory: a distribution tells us the probability of a random variable taking a particular value, or a value within a given set. The distribution of a continuous random variable $X$ is often expressed using a **probability density function** $p(x)$, defined such that
$$ \mathbb{P}(X \in [a, b]) = \int_a^b p(x) \,\mathrm{d}x, $$
but distributions can be much more general than this. 

For example, consider a 'random' variable $X$ that takes the value 0 with probability 1, and takes any other value with probability 0. If $X$ had a probability density function $p$, then $p(x) = 0$ for all $x \neq 0$ and yet $\int_{-\epsilon}^\epsilon p(x) = 1$ for any $\epsilon$. No ordinary function has such properties, as it would be infinite at $x = 0$. Instead, we introduce an object, the **Dirac delta function** $\delta(x)$, that has such properties. The **sampling property** of $\delta$ asserts that, for a 'suitable' functions $f$, 
$$
\int_a^b \delta(x) f(x) \,\mathrm{d}x = f(0)
$$
if $a < 0 < b$, and 0 otherwise. In probability language, this means
$$
\mathbb{E}f(X) = f(0),
$$
as one would expect for a random variable that (almost) certainly equals 0.

We can manipulate $\delta$ like other functions. In particular, since we can take linear combinations of $\delta(x-a)$ for different values of $a$, these shifted delta functions belong to a vector space, like ordinary functions. A linear combination of shifted delta functions can be used to represent the distribution of a discrete random variable.

In fact, distributions like $\delta$ live in a space $W$ of 'objects that you can multiply a function by, and then integrate' (_i.e._ take an inner product), as one does to calculate expected values. If we write $V$ for a space of 'suitable' functions, then the space of distributions $W$ can be identified as a subspace of $V^*$, the space of linear operators $V\rightarrow\mathbb{R}$. Some distributions are themselves functions, but objects such as $\delta$ are not. (And not all functions are distributions.)


## Convergence of distributions

Since $W \leq V^*$, we can consider what happens when we 'apply' a $p\in W$ to a function $f\in V$. Let us denote this using bra-ket notation $\langle p | f \rangle$. The analogy with inner products is useful because when $p$ is a function, we have
$$
\langle p | f \rangle = \int_{-\infty}^\infty p(x) f(x) \,\mathrm{d}x.
$$
The sampling property of the delta function can be written as
$$
\langle \delta | f \rangle = f(0).
$$

We can now talk about **convergence** in $W$. We say that a sequence of distributions $p_n \rightarrow p$ in the space $W$ if, for all 'suitable' functions, 
$$
\langle p_n | f \rangle \rightarrow \langle p | f \rangle.
$$
If the $p_n$ are the probability distributions of a sequence of random variables $X_n$, and $p$ is the probability distribution of $X$, then we say that the random $X_n$ **converge in distribution** towards $X$: equivalently, $\mathbb{E}f(X_n) \rightarrow \mathbb{E}(f(X))$ for all 'suitable' $f$.

Convergence towards a delta function is no different: say that a sequence of distributions $\delta_n \rightarrow \delta$ if 
$$\langle \delta_n | f \rangle \rightarrow \langle \delta | f \rangle = f(0).$$

## Sheet 3, question 9

A notable example of distributions converging towards the delta function is a sequence of increasingly sharp Gaussians:
$$
\delta_n(x) = \frac{n}{\pi^{1/2}} \exp\left(- n^2 x^2 \right).
$$
These are the probability distributions of normal random variables with smaller and smaller variance, $\sigma_n^2 = 1/(2n^2)$. 


